embedding_size: 1000
hidden_size: 256
model_path: models/
batch_size: 256
dropout: 0.5
tags:
  - organization
  - name
  - address
  - company
  - government
  - book
  - game
  - movie 
  - position
  - scene
  - chinese_political_party

